function withUnit(slug, path) {
  return slug ? `/${slug}${path}` : path;
}

export const ROUTES = {
  home: '/',
  unit: (slug) => (slug ? `/${slug}` : '/'),
  unitPage: (slug, pageSlug) => withUnit(slug, `/halaman/${pageSlug}`),
  unitPosts: (slug) => withUnit(slug, '/pengumuman'),
  unitPost: (slug, postSlug) => withUnit(slug, `/pengumuman/${postSlug}`),
  adminLogin: '/admin/login',
  adminDashboard: '/admin',
  adminUnits: '/admin/units',
  adminUnitNew: '/admin/units/new',
  adminUnitEdit: (id) => `/admin/units/${id}/edit`,
  adminPages: '/admin/pages',
  adminPageNew: '/admin/pages/new',
  adminPageNewBuilder: '/admin/pages/new/builder',
  adminPageEdit: (id) => `/admin/pages/${id}/edit`,
  adminPageBuilder: (id) => `/admin/pages/${id}/builder`,
  adminPagePreview: (id) => `/admin/pages/${id}/preview`,
  adminLandingBuilder: '/admin/landing/builder',
  adminLandingPreview: '/admin/landing/preview',
  adminPosts: '/admin/posts',
  adminPostNew: '/admin/posts/new',
  adminPostEdit: (id) => `/admin/posts/${id}/edit`,
  adminCategories: '/admin/categories',
  adminContentTypes: '/admin/content-types',
  adminContentTypeNew: '/admin/content-types/new',
  adminContentTypeEdit: (id) => `/admin/content-types/${id}/edit`,
  adminContentEntries: (typeId) => `/admin/content-types/${typeId}/entries`,
  adminContentEntryNew: (typeId) => `/admin/content-types/${typeId}/entries/new`,
  adminContentEntryEdit: (typeId, id) => `/admin/content-types/${typeId}/entries/${id}/edit`,
  unitData: (slug, key) => withUnit(slug, `/data/${key}`),
  unitDataEntry: (slug, key, entrySlug) => withUnit(slug, `/data/${key}/${entrySlug}`),
  adminMedia: '/admin/media',
  adminMenus: '/admin/menus',
  adminOrganization: '/admin/organization',
  adminAgendas: '/admin/agendas',
  adminAgendaNew: '/admin/agendas/new',
  adminAgendaEdit: (id) => `/admin/agendas/${id}/edit`,
  adminUsers: '/admin/users',
  adminUserNew: '/admin/users/new',
  adminUserEdit: (id) => `/admin/users/${id}/edit`,
  adminPermissions: '/admin/permissions',
  adminSeo: '/admin/seo',
  adminLanding: '/admin/landing',
  unitOrganization: (slug) => withUnit(slug, '/organisasi'),
  unitAgendas: (slug) => withUnit(slug, '/agenda'),
};
